steps:
- label: build
  env:
    GOPRIVATE: "github.com/segmentio"
    SEGMENT_CONTEXTS: "snyk,aws-credentials"
    SEGMENT_BUILDKITE_IMAGE: 'buildkite-agent-golang1.17'
  agents:
    queue: v1
  commands:
  - make vendor
  - make test

- label: publish
  env:
    SEGMENT_CONTEXTS: snyk,aws-credentials
    SEGMENT_BUILDKITE_IMAGE: buildkite-agent-golang1.17
  agents:
    queue: v1
  commands:
  - make publish branch=$BUILDKITE_BRANCH commit=$BUILDKITE_SHORT_COMMIT
